### ISSUE TITLE
My todo list

### ISSUE THREAD

**Issue by zerothi** [zerothi/sisl#522]
- [x] check COOP performance
- [x] check whether the k-choice in State.tile is correct, perhaps it should be the k-component of the lattice vector, since that is what tile does, i.e. check this for skewed cells (not needed since the k's is in unit-cells, dah
- [x] improve documentation on units.convert, it does not make sense
- [x] remove `_*` declarations in `electron` and `phonon` files
